### ISSUE TITLE
module 'bit' not found

### ISSUE THREAD

**Issue by PaxiTheAlchemist** [Hunter200165/Lua-Math-Parser#1]
Upon running
```bash
$ lua MathCalculator-Example.lua
```
I get an error telling me that the module `bit` was not found. Is there something I am missing to run the file? if so, could you please instruct me on how to retrieve this `bit` module?

Thank you in advance,
Paxi

**Comment by Hunter200165** [comment]
I am sorry for no response, github have not notified me of this issue. If it is still a thing - this parser is deprecated now, it is better to use new HMathParser, which is done by full analysis of input string and so on.
The error `module bit was not found` signals, that you have no module called `bit` with your current Lua installation. It may also be called `bit32`, just need to change name of module in HMathParser.lua at the top of the file (`require 'bit';` to `require bit32;`). But more chances that you have no bit module in any kind, means you need to install it yourself. Luarocks can help much in this situation

**Comment by Hunter200165** [comment]
New repository is https://github.com/Hunter200165/HMathParser
